package it.pedrazzi.marco.savemyphoto.WebService.Autogenerate;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.9.0
//
// Created by Quasar Development 
//
//---------------------------------------------------



import org.ksoap2.serialization.*;
import java.util.Vector;
import java.util.Hashtable;


public class RVKArrayOfString extends Vector< String> implements KvmSerializable
{
    
    public RVKArrayOfString(){}
    
    public RVKArrayOfString(java.lang.Object inObj,RVKExtendedSoapSerializationEnvelope __envelope)
    {
        if (inObj == null)
            return;
        SoapObject soapObject=(SoapObject)inObj;
        int size = soapObject.getPropertyCount();
        for (int i0=0;i0< size;i0++)
        {
            java.lang.Object obj = soapObject.getProperty(i0);
            if (obj!=null && obj instanceof AttributeContainer)
            {
                AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
                String j1= j.toString();
                add(j1);
            }
        }
}
    
    @Override
    public java.lang.Object getProperty(int arg0) {
        return this.get(arg0)!=null?this.get(arg0):SoapPrimitive.NullNilElement;
    }
    
    @Override
    public int getPropertyCount() {
        return this.size();
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        info.name = "string";
        info.type = PropertyInfo.STRING_CLASS;
    	info.namespace= "http://it.pedrazzi.marco.savemyphoto/";
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }

    
}